### ISSUE TITLE
installing

### ISSUE THREAD

**Issue by 4e-ie** [avalon60/ctk_theme_builder#35]
no path found

**Comment by avalon60** [comment]
I can only guess at the issue here - not much detail.

Have you specified the full pathnames for both the -i <install_base> -p <package_zip_file> 
?

Linux example:

python3 theme_builder_setup.py -i /home/clive -p /home/clive/Downloads/ctk_theme_builder-3.0.2.zip

Windows example:

python3 theme_builder_setup.py -i C:\apps -p c:\Users\clive\Downloads\ctk_theme_builder-3.0.2.zip

PS: Using full pathnames should not be necessary when version 3.1 is released.

**Comment by avalon60** [comment]
Please see README, which is updated - don't install from Code button. Download from the releaes link on the right hand side of the same page.

**Comment by avalon60** [comment]
Please see README, which is updated - don't install from Code button. Download from the releaes link on the right hand side of the same page.
